# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddiet', '0003_auto_20160730_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='item_coefficient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ml_coefficient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdata',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ddiet.Product'),
        ),
    ]
