# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiet', '0004_auto_20160731_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='data',
            field=models.DateField(),
        ),
    ]
