# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddiet', '0005_auto_20160731_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='data',
            new_name='eat_date',
        ),
    ]
