# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ddiet', '0006_auto_20160731_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='amount',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
