# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiet', '0007_productdata_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
