# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddiet', '0008_auto_20160804_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductData',
        ),
    ]
