# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddiet', '0009_auto_20160804_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat_date', models.DateField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ddiet.Product')),
            ],
        ),
    ]
